### ISSUE TITLE
Explore how to improve sponsors list

### ISSUE THREAD

**Issue by kowalski7cc** [unixMiB/LinuxDayMilano#15]
Maybe a carousel with 4-6 logos in it?

**Comment by EndBug** [comment]
This will do:

> {GCE logo}
> Federico Grandi, GitHub Campus Expert - _«Da quando ho conosciuto questa community vi ho sempre trovato persone competenti e appassionate. Invito tutti a partecipare al Linux Day Milano 2022 all'università Bicocca e venirli a conoscere ✨»_

If you can't use the sparkles emoji an exclamation mark will be fine ahahha

**Comment by valerio-bozzolan** [comment]
That's awesome! Proposed changes:

-vi ho
+ho

-venirli a conoscere
+venire a conoscerli

**Comment by EndBug** [comment]
Italian: 100

> {GCE logo}
> Federico Grandi, GitHub Campus Expert - «Da quando ho conosciuto questa community ho sempre trovato persone competenti e appassionate. Invito tutti a partecipare al Linux Day Milano 2022 all'università Bicocca e venire a conoscerli ✨»

**Comment by valerio-bozzolan** [comment]
Grammar nazi test: passed. I've updated my comment to reflect your work:

https://github.com/unixMiB/LinuxDayMilano/issues/15#issuecomment-1278575879
